name: Aggregate GitHub Stats

on:
  schedule:
    # Runs at 12:00 every day
    - cron: "0 12 * * *"
  workflow_dispatch:  # Allows manual trigger
  # You can also add triggers like push or pull_request if needed

permissions:
  contents: write

jobs:
  aggregate:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code (required)
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up Python environment
    - name: Set up Python 3
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    # Step 3: Install required dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    # Step 4: Set environment variables
    - name: Set environment variables and run python
      env:
        USER_NAME: ${{ secrets.USER_NAME }}
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: python .github/scripts/aggregate.py

    # Step 5: Commit the updated stats (if necessary)
    - name: Commit results
      env:
        PAT_TOKEN: ${{ secrets.WRITE_TOKEN }}
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Action"
        git add profile/README.md
        git commit -m "Updated GitHub stats"
        git push https://x-access-token:${{ secrets.WRITE_TOKEN }}@github.com/${{ github.repository }} HEAD:main
      continue-on-error: true  # Avoid failure if nothing to commit
